# Generated by Django 2.2.5 on 2020-03-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200303_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tickets_num',
        ),
    ]
